# Generated by Django 4.2.23 on 2025-06-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_auth_detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customcompanyuser',
            old_name='comapny_email',
            new_name='company_email',
        ),
    ]
